const WebSocket = require('ws')
const fs = require('fs');
const path = require('path');


const commands = {
  w: "f",
  a: "l",
  s: "b",
  d: "r"
}

const image = document.getElementById("stream-image")
const snapBtn= document.getElementById("snap-btn")

let currentFrame = null

const server = new WebSocket('ws://localhost:8080');


server.on('open', function open() {
  console.log('Cmd socket connected.');
  server.send("client_password")
})


server.on('message', function incoming(data) {
  console.log("A message")
  currentFrame = `data:image/jpeg;base64,${data}`
  image.src = currentFrame
})

document.addEventListener("keydown", e => {
    //by pressing "Q" letter on your keyboard, the bulgarian keyboard will print "," (a comma) and you will get the value of the key being pressed
    console.log(e.key); // prints ","
    if (commands[e.key] !== undefined){
      const data = {
        method: "command",
        cmd: commands[e.key]
      }
      server.send(JSON.stringify(data))
    }
    else {
      console.log("invalid command.")
    }
    
})

snapBtn.addEventListener("click", e => {
  // string generated by canvas.toDataURL()
  const img = currentFrame

  // strip off the data: url prefix to get just the base64-encoded bytes
  const data = img.replace(/^data:image\/\w+;base64,/, "");

  const buf = new Buffer(data, 'base64');

  let current = new Date()
  current = current.toISOString()

  const imgPath = path.join(__dirname, "images", `${current}.png`)
  fs.writeFile(imgPath, buf, error => {

    console.log("Finish")
    console.log(error)
  });

})
