const WebSocket = require('ws')
const fs = require('fs');
const path = require('path');


const image = document.getElementById("stream-image")
const snapBtn= document.getElementById("snap-btn")

let currentFrame = null

const ws_cmd = new WebSocket('http://127.0.0.1:8000/ws/cmd');
const ws_fetch_stream = new WebSocket('ws://localhost:9000');


ws_fetch_stream.on('open', function open() {
  console.log('Stream socket connected.');
})
ws_cmd.on('open', function open() {
  console.log('Cmd socket connected.');
})

ws_fetch_stream.on('message', function incoming(data) {
  currentFrame = `data:image/jpeg;base64,${data}`
  image.src = currentFrame
})

ws_cmd.on('message', function incoming(data) {
  console.log(data)
})

document.addEventListener("keydown", e => {
    //by pressing "Q" letter on your keyboard, the bulgarian keyboard will print "," (a comma) and you will get the value of the key being pressed
    console.log(e.key); // prints ","
    ws_cmd.send(e.key)
})

snapBtn.addEventListener("click", e => {
  // string generated by canvas.toDataURL()
  const img = currentFrame

  // strip off the data: url prefix to get just the base64-encoded bytes
  const data = img.replace(/^data:image\/\w+;base64,/, "");

  const buf = new Buffer(data, 'base64');

  let current = new Date()
  current = current.toISOString()

  const imgPath = path.join(__dirname, "images", `${current}.png`)
  fs.writeFile(imgPath, buf, error => {

    console.log("Finish")
    console.log(error)
  });

})
